import { NagPackSuppression } from 'cdk-nag';

/**
 * cdk-nag suppressions for the VoC Data Lake project
 * Add suppressions here as we review and approve them
 */

// CDK Custom Resource Lambdas (managed by CDK, not our code)
export const cdkCustomResourceSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-L1',
    reason: 'CDK-managed custom resource Lambda functions use CDK-controlled runtimes',
  },
];

// DynamoDB PITR for idempotency table
export const idempotencyTableSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-DDB3',
    reason: 'Idempotency table has 15-minute TTL - transient data does not require point-in-time recovery',
  },
];

// S3 access logging for CloudFront-fronted buckets
export const websiteBucketSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-S1',
    reason: 'Website bucket is served exclusively through CloudFront - CloudFront access logs provide traffic visibility',
  },
];

// AWSLambdaBasicExecutionRole - AWS managed policy for Lambda CloudWatch logging
export const lambdaBasicExecutionRoleSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM4',
    reason: 'AWSLambdaBasicExecutionRole is AWS-recommended managed policy for Lambda CloudWatch logging with minimal permissions',
    appliesTo: ['Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'],
  },
];

// AmazonAPIGatewayPushToCloudWatchLogs - AWS managed policy for API Gateway to publish logs to CloudWatch 
export const apiGatewayPushToCloudwatchLogsRoleSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM4',
    reason: 'AmazonAPIGatewayPushToCloudWatchLogs is AWS-recommended managed policy for API Gateway to push to CloudWatch logging with minimal permissions',
    appliesTo: ['Policy::arn:<AWS::Partition>:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs'],
  },
];

// CloudFront distributions using default certificate
export const cloudfrontDefaultCertSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-CFR1',
    reason: 'Geo restrictions not required for sample application - can be enabled based on specific compliance requirements',
  },
  {
    id: 'AwsSolutions-CFR2',
    reason: 'AWS WAF not included to minimize costs for sample deployment - recommended for production use',
  },
  {
    id: 'AwsSolutions-CFR4',
    reason: 'CloudFront distributions using default certificate (*.cloudfront.net) are limited to TLSv1 by AWS - custom domain with ACM certificate required for TLSv1.2+. See: https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-properties-cloudfront-distribution-viewercertificate.html#cfn-cloudfront-distribution-viewercertificate-minimumprotocolversion',
  },
];

// Cognito User Pool security settings
export const cognitoSecuritySuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-COG2',
    reason: 'MFA not enforced by default to reduce friction for sample application - users can enable MFA in their account settings',
  },
  {
    id: 'AwsSolutions-COG3',
    reason: 'Cognito Advanced Security Mode not enforced to minimize costs for sample deployment ($0.05 per login attempt) - recommended for production use',
  },
];

// Secrets Manager rotation for API credentials
export const apiSecretsSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-SMG4',
    reason: 'Secret contains third-party API credentials that cannot be automatically rotated by AWS - requires manual rotation through provider portals',
  },
];

// DynamoDB Global Secondary Index access
export const dynamoDbGsiSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM5',
    reason: 'Wildcard required for DynamoDB Global Secondary Index access - GSI ARNs follow pattern <TableArn>/index/* per AWS best practices',
    appliesTo: [
      { regex: '/Resource::<.*FeedbackTable.*\.Arn>/index/\*/' },
      { regex: '/Resource::<.*AggregatesTable.*\.Arn>/index/\*/' },
      { regex: '/Resource::<.*ProjectsTable.*\.Arn>/index/\*/' },
      { regex: '/Resource::<.*JobsTable.*\.Arn>/index/\*/' },
    ],
  },
];

// KMS encryption operations - CDK grantEncryptDecrypt() uses wildcards
export const kmsEncryptionSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM5',
    reason: 'KMS wildcard actions (GenerateDataKey*, ReEncrypt*) are generated by CDK grantEncryptDecrypt() construct - covers multiple related encryption operations',
    appliesTo: [
      'Action::kms:GenerateDataKey*',
      'Action::kms:ReEncrypt*',
    ],
  },
];

// S3 bucket operations - CDK grantReadWrite() and grantRead() use wildcards
export const s3BucketSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM5',
    reason: 'S3 wildcard actions are generated by CDK bucket grant methods (grantReadWrite, grantRead) - covers related S3 operations',
    appliesTo: [
      'Action::s3:Abort*',
      'Action::s3:DeleteObject*',
      'Action::s3:GetBucket*',
      'Action::s3:GetObject*',
      'Action::s3:List*',
    ],
  },
  {
    id: 'AwsSolutions-IAM5',
    reason: 'S3 object access requires wildcard on bucket ARN (bucket-arn/*) - AWS best practice for object-level permissions',
    appliesTo: [
      { regex: '/.*RawDataBucket.*\.Arn>/\*/' },
      { regex: '/.*S3ImportBucket.*\.Arn>/\*/' },
      { regex: '/.*WebsiteBucket.*\.Arn>/\*/' }
    ],
  },
];

// Bedrock foundation model ARNs - region wildcard required
export const bedrockModelSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM5',
    reason: 'Bedrock foundation model ARNs require region wildcard as models are cross-region resources',
    appliesTo: [
      'Resource::arn:aws:bedrock:*::foundation-model/anthropic.claude-haiku-4-5-20251001-v1:0',
      'Resource::arn:aws:bedrock:*::foundation-model/anthropic.claude-sonnet-4-6',
      { regex: '/Resource::arn:aws:bedrock:\\*:.*:inference-profile/global\\.anthropic\\.claude-sonnet-4-6/' },
      { regex: '/Resource::arn:aws:bedrock:\\*:.*:inference-profile/global\\.anthropic\\.claude-haiku-4-5-20251001-v1:0/' },
    ],
  },
];

// Dynamic plugin system - Lambda and EventBridge wildcards
export const pluginSystemSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM5',
    reason: 'Plugin system requires wildcards for dynamic Lambda function names and EventBridge rules created at runtime',
    appliesTo: [
      { regex: '/Resource::arn:aws:lambda:.*:.*:function:voc-ingestor-webscraper-\*/' },
      { regex: '/Resource::arn:aws:lambda:.*:.*:function:voc-ingestor-\*/' },
      { regex: '/Resource::arn:aws:lambda:.*:.*:function:voc-manual-import-processor-\*/' },
      { regex: '/Resource::arn:aws:lambda:.*:.*:function:voc-projects-api-\*/' },
      { regex: '/Resource::arn:aws:events:.*:.*:rule.voc-ingest-.*-schedule/' },
    ],
  },
  {
    id: 'AwsSolutions-IAM5',
    reason: 'Lambda version/alias wildcard required for Step Functions state machine invocations and async job Lambda invocations',
    appliesTo: [
      { regex: '/Resource::<.*ResearchStepLambda.*\.Arn>:\*/' },
      { regex: '/Resource::<.*ModelAgreementLambda.*\.Arn>:\*/' },
      { regex: '/Resource::<.*PersonaGeneratorJob.*\.Arn>:\*/' },
      { regex: '/Resource::<.*DocumentGeneratorJob.*\.Arn>:\*/' },
      { regex: '/Resource::<.*DocumentMergerJob.*\.Arn>:\*/' },
      { regex: '/Resource::<.*PersonaImporterJob.*\.Arn>:\*/' },
    ],
  },
];

// CDK deployment assets
export const cdkAssetsSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM5',
    reason: 'CDK bootstrap bucket wildcard required for deployment assets',
    appliesTo: [
      { regex: '/Resource::arn:aws:s3:::cdk-.*-assets-.*/' },
    ],
  },
];

// Bedrock foundation model agreement APIs - account-level operations
export const bedrockAgreementSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM5',
    reason: 'Bedrock foundation model agreement APIs (ListFoundationModelAgreementOffers, CreateFoundationModelAgreement, GetFoundationModelAvailability, PutUseCaseForModelAccess) are account-level operations that do not support resource-level permissions',
    appliesTo: ['Resource::*'],
  },
];

// AWS Marketplace - subscription APIs for Bedrock model access
export const marketplaceSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM5',
    reason: 'AWS Marketplace subscription APIs (ViewSubscriptions, Subscribe) do not support resource-level permissions - required for Bedrock model EULA acceptance',
    appliesTo: ['Resource::*'],
  },
];

// AWS Comprehend - real-time text analysis APIs
export const comprehendSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM5',
    reason: 'Comprehend real-time detection APIs (DetectSentiment, DetectKeyPhrases, DetectDominantLanguage) do not support resource-level permissions - these are stateless analysis operations that require Resource:*',
    appliesTo: [
      'Resource::*',
    ],
  },
];

// AWS Translate - real-time translation API
export const translateSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-IAM5',
    reason: 'Translate TranslateText API requires Resource:* for real-time translation without custom parallel data - parallel data ARNs only apply when using custom terminology/translation memories',
    appliesTo: [
      'Resource::*',
    ],
  },
];

// API Gateway request validation
export const apiGatewayRequestValidationSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-APIG2',
    reason: 'Request validation handled by Lambda functions with comprehensive input validation using Pydantic models and custom logic',
  },
  {
    id: 'AwsSolutions-APIG3',
    reason: 'AWS WAF not included to minimize costs for sample deployment - recommended for production use',
  },
];

// Public feedback form endpoints (intentionally unauthenticated)
export const publicFeedbackEndpointSuppressions: NagPackSuppression[] = [
  {
    id: 'AwsSolutions-APIG4',
    reason: 'Feedback form endpoints are intentionally public to allow anonymous customer feedback submission',
  },
  {
    id: 'AwsSolutions-COG4',
    reason: 'Feedback form endpoints are intentionally public to allow anonymous customer feedback submission - Cognito authentication would prevent external users from submitting feedback',
  },
];
